### ISSUE TITLE
issus with php 8.1 

### ISSUE THREAD

**Issue by neilchuang1** [pnp4nagios/pnp4nagios#74]
I installed pnp4nagios 0.6.26 on Rocky Linux 8.10. PHP 8.1.30, I adjusted the install.php, and it seems to have passed the [pnp4nagios environment test,](https://meee.com.tw/liTGm79)

but after removing the install.php, 
the error 

> `"Fatal error: Uncaught Error: Undefined constant "MB_OVERLOAD_STRING" in /usr/local/pnp4nagios/lib/kohana/system/core/utf8.php:52 Stack trace: #0 /usr/local/pnp4nagios/lib/kohana/system/core/Bootstrap.php(32): require() #1 /usr/local/pnp4nagios/share/index.php(145): require('/usr/local/pnp4...') #2 {main} thrown in /usr/local/pnp4nagios/lib/kohana/system/core/utf8.php on line 52"`

 appears. How can I fix this problem? Or do I need to reinstall it on a new VM like the[ article](https://github.com/pnp4nagios/pnp4nagios/issues/65)?

**Comment by celane** [comment]
The current release is 0.6.27-5, you might want
to try that, although the "MB_OVERLOAD_STRING" sounds
a lot like 'old software not getting cleared out
with upgrade'. 

On Thu, 10 Oct 2024 21:27:34 -0700
neilchuang1 ***@***.***> wrote:

> I installed pnp4nagios 0.6.26 on Rocky Linux 8.10. I adjusted the
> install.php, and it seems to have passed the pnp4nagios environment
> test, [https://meee.com.tw/liTGm79](url)
> 
> but after removing the install.php, 
> the error 
> 
> > `"Fatal error: Uncaught Error: Undefined constant
> > "MB_OVERLOAD_STRING" in
> > /usr/local/pnp4nagios/lib/kohana/system/core/utf8.php:52 Stack
> > trace: #0
> > /usr/local/pnp4nagios/lib/kohana/system/core/Bootstrap.php(32):
> > require() #1 /usr/local/pnp4nagios/share/index.php(145):
> > require('/usr/local/pnp4...') #2 {main} thrown in
> > /usr/local/pnp4nagios/lib/kohana/system/core/utf8.php on line 52"`  
> 
>  appears. How can I fix this problem? Or do I need to reinstall it on
> a new VM like the[
> article](https://github.com/pnp4nagios/pnp4nagios/issues/65)?
> 



-- 
Drexel University  |/             /    ·   ν ·   Chuck Lane   |D
======]－－－>－－－C－－－－－π+－－<                Disque 911  |U
Particle Physics    \             \    ~~ e+~~   215-895-1545 |N
***@***.***                    －​μ+－－+νν                 |E
